### ISSUE TITLE
Nested array escaping not working correctly

### ISSUE THREAD

**Issue by alexandreroche** [felixge/node-mysql#1018]
I seem to be running into an issue here:

> console.log(require('mysql').format('INSERT INTO table (col1, col2) VALUES ?', [['hi', 'yes'], ['bye', 'no']]));

This currently returns (on latest version 2.5.5):
> INSERT INTO table (col1, col2) VALUES 'hi', 'yes'

Shouldn't it be returning the following...?
> INSERT INTO table (col1, col2) VALUES ('hi', 'yes'), ('bye', 'no')

Was looking through the code and don't see any glaring issues.

**Comment by alexandreroche** [comment]
Okay wait, I think it's getting confused because passing an array to .format() is also how you specify multiple parameters to format. But shouldn't it be smart enough to realize that I'm only escaping one value (hence the single '?' in my SQL statement)?

At any rate, the solution is to put your nested array inside another array, as the first parameter:
> console.log(require('mysql').format('INSERT INTO table (col1, col2) VALUES ?', [[['hi', 'yes'], ['bye', 'no']]]));

Which results in the proper formatting:
> INSERT INTO table (col1, col2) VALUES ('hi', 'yes'), ('bye', 'no')

**Comment by dougwilson** [comment]
Yes, you got in in your update: you were simply passing the wrong value in to `.format`. The value takes an array, and since you need to pass in an array or arrays, you need to have three levels of arrays in the end: the first level is the array of values, where each element in the array corresponds to a `?` (think `[val1]`). Then you need `val1` to be an array of arrays (think `val1 = [['a', 'b'], ['c', 'd']]`). Now, if you put those together, you end up with `[[['a', 'b'], ['c', 'd']]]`.

**Comment by dougwilson** [comment]
The fact that you can do a single value was a big API mistake and I intend to remove it whenever the next major arrives. You should always pass in an array of values.

**Comment by alexandreroche** [comment]
Yeah, that's a good point. I'll make sure to always pass in an array to avoid confusion :)

**Comment by sidorares** [comment]
> The fact that you can do a single value was a big API mistake and I intend to remove it whenever the next major arrives. You should always pass in an array of values.

I feel the same ( I was actually not aware for a long time that values param is converted to array if it's not array ). I don't think anyone will notice, but yes, that's major version semver wise
