### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by chacent** [felixge/node-mysql#1022]
i want to sync some data from mysql to sqlserver,and sql server may busy,it will take some time and i pause mysql connection,when time span take about 60s and then resume the mysql connection, an error occur, `Error: Connection lost: The server closed the connection.`,mysql server close the connection,how can i resolve the problem? 
i can't reconnect mysql,because i want to deal the recordset continue;

**Comment by dougwilson** [comment]
The problem is that your server is currently configured to close the connection quickly. You can do two things to help solve this:

1. Don't call `.pause()` and instead buffer up all the results yourself. This will ensure the results flow from the server instead of keeping the connection idle. The downside is you'll need to fit all the results in memory on your Node.js process.
2. Adjust the timeout on your MySQL server settings. You'll want to tweak the [wait_timeout setting](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_wait_timeout).
