### ISSUE TITLE
Sorry,but issue not resolved.Error: Connection lost: The server closed the connection

### ISSUE THREAD

**Issue by chacent** [felixge/node-mysql#1023]
https://github.com/felixge/node-mysql/issues/1022,
I'm not sure that you will care this issue if i conntine in last thread,so i write a new report.

you have give me two solutions,both is not useful.
the first one,recordset is very large, if i buffer it in memory ,nodejs will crash.
the last one,i had setted wait_timeout and interactive_timeout, but it isn't what i wanted.in my case it isn't useful.

i can descript it simply,
connection.connect()->
query("select * from table")//where table is very large,and record is also very large->
fetch(count)//where count is great than 0,for example 100->
sleep(ms)//ms is a long time->
fetch(count)// if last ms between 1-45000,verything is ok,but if ms great than about 50000,
error occured

**Comment by dougwilson** [comment]
Please don't make new issues to continue a conversation; there is no reason you cannot just post follow ups in the previous issue. Your issue is purely due to your MySQL server configuration, rather than this module. I believe you are actually running into the [net_write_timeout setting](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_net_write_timeout), so I was mistaken on which setting from before. Try bumping that setting to 120 or something.

Another option is that if you are not going to read fast enough to prevent your MySQL server from timing out your connection, you may want to simply make multiple queries using `LIMIT` instead of a single big query and trying to read it really slow.

**Comment by chacent** [comment]
thanks, i see.
i think you are right ,i will try the first resolution.
but i don't think the twice is a good one

**Comment by dougwilson** [comment]
Ok. I'm also sorry that I don't always understand what you are saying :( In the end, the issue you are having cannot be solved by this library. You have to either tweak your MySQL server settings to change the way in which you are performing your query.

You may also want to look into other node.js MySQL libraries like "mysql2" in case they behave in a way more compatible with your workflow.
