### ISSUE TITLE
Simple query takes 2+ minute to complete (99% of time takes in  ComQuitPacket command)

### ISSUE THREAD

**Issue by ppbsi** [felixge/node-mysql#1034]
I have a simple table and insert query. It takes 2+ min to complete the process with MySQL-node module. Following is the debug output. The last command `ComQuitPacket` is where the process is waiting but don't know why. Can you please check and let me know if there is any fix? Thanks.

MySQL-node version - 2.5

Query
```sql
insert into monitor.job_history (name,rundate,result,msg) values('sps_cn_sync.sh','2015-03-20',0,'fixm')
```
```
Debug output
<-- HandshakeInitializationPacket
{ protocolVersion: 10,
  serverVersion: '5.5.41-0ubuntu0.14.10.1',
  threadId: 37,
  scrambleBuff1: <Buffer 36 28 62 38 2e 7d 4f 53>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63487,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 32783,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 30 36 5c 4d 4d 79 3c 5b 36 3b 66 71>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true }

--> ClientAuthenticationPacket
{ clientFlags: 455631,
  maxPacketSize: 0,
  charsetNumber: 33,
  filler: undefined,
  user: 'monuser',
  scrambleBuff: <Buffer ee 5e c5 11 b4 75 4f 26 59 b8 7e d5 d4 f9 47 09 f1 7e 37 65>,
  database: undefined,
  protocol41: true }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }

--> ComQueryPacket
{ command: 3,
  sql: 'insert into monitor.job_history (name,rundate,result,msg) values(\'sps_cn_sync.sh\',\'2015-03-20\',0,\'fixm\')' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }

--> ComQuitPacket
{ command: 1 }
```
```
GET /writehistory?name=sps_cn_sync.sh&rundate=2015-03-20 200 120099ms
```

**Comment by dougwilson** [comment]
The reason the `ComQuitPacket` would wait would be if your network is dropping the final `FIN-ACK` TCP packets.

**Comment by dougwilson** [comment]
If you want to confirm that you're having a network issue, you can run your script with the environment variable set `NODE_DEBUG=net` and paste the end of that trace, though it's going to be really hard to read if you are running this inside a web server, since all the web server's `net` traffic will be intermingled.

You can also use something like Wireshark to confirm.

Basically, without those TCP packets, we don't know if the connection has ended. We just eventually timeout.

Another option is that you can always call `.end` with a really short timeout and don't care if the end timesout: `conn.end({timeout: 1000}, function (err) {})`

**Comment by dougwilson** [comment]
Please let me know if you need additional assistance.
