### ISSUE TITLE
Query stream pausing and memory concerns

### ISSUE THREAD

**Issue by unlucio** [felixge/node-mysql#1049]
Hello,
we're quite happily using the query stream features and were wondering about a couple of points:
- when pausing the stream: does mode-mysql keep reading from my server, thus buffering the results until the next resume()? (I read the doc but some points kind of hint yes, and others rise doubts)
- Can queuing a good amount (~200 ish up to thousands) of queries on a single connection have any side effect? (we're not using cluster pools)

We're dealing with both lots of small queries in a short amount of time as well as queries potentially producing sizable amount of results (100K+ or millions,   ~4G of data as order of magnitude), and currently investigating a memory issue while seeing our process spike up to 1G+ used memory (res). 

The application doesn't have many moving parts: it basically streams data from one mysql DB to another destination (mysql, elastic search, etc).

Obtaining heapdumps shows a large amount of memory use in strings that resembles the "raw" form of our data.

Depending on the destination we might need to throttle the result stream: processes needing to pause/resume the source stream showed to eat way more memory than those not needing it:
800 MB to 1.2G vs 500ish MB (which is till a lot and way more than we'd expect).

Unfortunately as for now I don't have any real snipped code I can share to try to reproduce the problem since it show up only with a good deal of traffic.

Thanks for any help or suggestion.

cheers
lucio

**Comment by dougwilson** [comment]
> when pausing the stream: does mode-mysql keep reading from my server, thus buffering the results until the next resume()? 

Hi! So as far as what happens, when you cause `.pause()` we immediately stop parsing the incoming bytes from the connection and ask the Node.js socket to stop reading from the network (what the Node.js socket does, exactly, would be a question for Node.js core maintainers). We do no buffering at all in this module, so after the `.pause()` no work is done in this module (but like I said, Node.js's socket may still be doing something, IDK).

> Can queuing a good amount (~200 ish up to thousands) of queries on a single connection have any side effect? 

No, it would not have any (real) effect. The reason is the MySQL protocol is serial and can only perform each query one-by-one. The only thing queuing a lot of queries up is just using the small amount of memory it takes to hold a reference to your callback, whatever data that function closes over in your code, and the SQL string.

**Comment by dougwilson** [comment]
Hi @unlucio any other questions/concerns?
