### ISSUE TITLE
Regarding: TIME (could be mapped to Date, but what date would be set?)

### ISSUE THREAD

**Issue by krnlde** [felixge/node-mysql#1051]
You could represent them as durations like in: http://momentjs.com/docs/#/durations/creating/

**Comment by dougwilson** [comment]
Assuming we want to even add a dependency on moment, which we don't. We provide a framework so you can easily covert TIME columns to moment objects if you desire that.

**Comment by krnlde** [comment]
The format moment uses is a standard. You don't actually have to have moment for that. But the description there was thorough.

**Comment by dougwilson** [comment]
Well, I'm not sure what we would be doing if not actually using moment? Anything as a string is just what your own MySQL server sends back to us...

**Comment by krnlde** [comment]
Yep.

**Comment by dougwilson** [comment]
Ok. That's what already happens. I'm going to close this question since I'm not sure what it really is. Please feel free to elaborate if there is still something to do here.

**Comment by krnlde** [comment]
Not really an issue. It was more meant to be a suggestion for further consideration.

**Comment by dougwilson** [comment]
Right, but we don't do anything; it's just what your server sends back as the `TIME` format. If you change your MySQL server's response to be in that format, then it'll be like that in your queries here. We are a low-level library that tries not to touch whatever is coming back from your server. There really isn't anything for us to consider here, since we don't control the MySQL server source :)

**Comment by krnlde** [comment]
True. I just answered the question in the readme.MD :)
