### ISSUE TITLE
object query 

### ISSUE THREAD

**Issue by lordard** [felixge/node-mysql#1090]
hi 
I got a problem when i use connection.query () 
the code is like this
```
connection.query( 'select * from users where ?' , cfg , fcb );
```
It's great if there is only one setting in cfg.   ->  `cfg = { id : 1234 };`
But If i assign multiple objects in cfg , the query failed . -> `cfg = {name:hello, sex:M, Country:USA };`
I found the issue after I check the query.sql 
the sql command had been build like this :
```
'select * from users where name=hello, sex=M, country=USA'
```
but , as my understanding about sql , the command should be 
```
'select * from users where name=hello and sex=M and country=USA'
```
So , I trace the codes and modified the function ( "objectToValues" ) in  mysql\lib\protocol\sqlString.js 
Just replace the 
`return values.join(', ');`           to    
`return values.join(' and '); `

It seems solved .

Is there any side effect ?

**Comment by dougwilson** [comment]
Hi, yes, that change would break a lot of people. The `?` object-style replacements are only for use in `SET` and similar statements, rather than for use in the `WHERE` clause. If you are looking to dynamically build complex SQL and WHERE clauses, you may want to try using https://hiddentao.github.io/squel/

```js
var query = squel.select()
  .table('users')
  // your stuff
  .toParam();
connection.query(query.text, query.values, function (err, rows) {
  // ...
});
```
