### ISSUE TITLE
it will not query anymore

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1105]
@dougwilson ,

can I ask,why is it that if I will not use the node mysql,like I am navigating to other menu, there is no db involve after 5 min or more,then I will go back to page where db is involve,when I look at in my server.js the pool.getconnection() is not firing anymore.

this is only my set up in my server.js

```javascript
    var pool = mysql.createPool({

    host: 'localhost',
    user: 'root',
    password: '',
    dateStrings: true,
    database: 'mydb'


});


```

Thank you in advance.

**Comment by dougwilson** [comment]
If `pool.getConnection()` is not firing any longer (as in, you are calling it and it's not calling your callback), it's because you are missing a `connection.release()` somewhere and are leaking connections; `pool.getConnection()` is thus just waiting for you to call `connection.release()` before it calls your callback.

**Comment by ezekel** [comment]
Thank you, I will trace my code.
