### ISSUE TITLE
Cannot use multi-database query

### ISSUE THREAD

**Issue by dlabey** [felixge/node-mysql#1146]
It would be nice to support this so a cross-database JOIN could be achieved

**Comment by dougwilson** [comment]
As far as I know, you can definitely do cross-database JOIN calls with this library, right @sidorares ? @dlabey can you give an example of what you are trying to do that doesn't work? Anything you can do at the `mysql` command line prompt, this library can do.

**Comment by sidorares** [comment]
As far as I know, yes ( if your credentials allow access to both databases )

@dlabey can you give example query that fails for you? I can definitely mix data from "mysql.user" with my test db tables

**Comment by dougwilson** [comment]
I was able to get multi-database queries to work just fine. It's possible you are connect with a user that does not have the proper grants to the other database, etc. I'm going to close this issue due to lack of response and reproduction, but please feel free to post back here when you get more information :)
