### ISSUE TITLE
About unexpected failure occur in poolCluster.getConnection if the server restart

### ISSUE THREAD

**Issue by vc05946** [felixge/node-mysql#1156]
Hello! I have used the poolCluster feature and I would like to ask about a issue for the unexpected failure in the `poolCluster.getConnection`.

The situation is that : 

```js
// I have used "later" and "mysql"

var clusterConfig = {
	removeNodeErrorCount : 15
};

var poolCluster = mysql.createPoolCluster(clusterConfig);

var cluster_config = {
  host     : setting.db_cluster_host     ,
  user     : setting.db_cluster_user     ,
  password : setting.db_cluster_password ,
  database : setting.db_cluster_database 
};

poolCluster.add('CLUSTER1', cluster_config);

var sched = later.parse.recur().every(1).second();

var alertJob = function(val) {
   poolCluster.getConnection('CLUSTER*',function (err, connection) {
       console.log("Inside cluster");
   });
}

later.setInterval(alertJob, sched);
```

The program would run the cronjob every second. If I stopped the server and restart it, the "getConnection" can only run successfully for around 10 times only and no respond replied afterward.

Would there be any factor which would hinder the "getConnection" to run successfully once the server restart ?

**Comment by dougwilson** [comment]
By default once a node is removed it is never added back. You would need to use the  restoreNodeTimeout option so it does get added back.

**Comment by vc05946** [comment]
Thanks for your reply. 

But the situation seems like even if the node restored (when server finish restart) before it is removed, the 'getConnection' callback "function(err,connection)" would stop running after few cronjob cycle.

**Comment by dougwilson** [comment]
Hi @vc05946 , have you tried the `restoreNodeTimeout` option yet? The behavior you are describing is the expected behavior if you are not using the `restoreNodeTimeout` option _and_ version 2.6.0 or higher of this module.

Please ensure that your module version is 2.6.0 or higher and you are specifying a value for the `restoreNodeTimeout` option. You can find more information on the options to pool cluster here: https://github.com/felixge/node-mysql#poolcluster-option
