### ISSUE TITLE
What is the fastest way to get the auto_increment value from a table?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1159]
Topic.

Say my db has 100 rows, and my id is auto increment. So the next one is 101, but how do I get this dynamically?

**Comment by AdriVanHoudt** [comment]
Why do you need this?

**Comment by McFarts** [comment]
Basically if a player kills a monster it will drop items into the buffer but they all need a unique index that increments from the rpg_user_items auto increment value

**Comment by AdriVanHoudt** [comment]
Do you create the drops by inserting them into the db? Normally the db takes care of auto increment for example I make a user object, insert it into the db, you get the `results.insertId` back (if inserting 1 thing) and you bind that to the id of the user object and there you go, a user with the Id
You could also make your own global counter but that is way harder because you have to deal with reboots and stuff

**Comment by McFarts** [comment]
Yeah I forgot when inserting to the db, it automatically increments it, my bad bro sorry about that.

**Comment by AdriVanHoudt** [comment]
np, if I answered your question you may close the issue ;)
