### ISSUE TITLE
node-mysql crashes nodejs app after certain inactivity

### ISSUE THREAD

**Issue by amolkedar** [felixge/node-mysql#1167]
So i am writing a nodejs webservice that will accept JSON and enter it into a mysql table.
my service works fine if no data is passed to it and does not timeout, but as soon as i send a request with JSON data and then the data is entered into the mysql table. Once that is done the node app gets killed with the following error
```
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/akedar/sqlconnector/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/akedar/sqlconnector/node_modules/mysql/lib/Connection.js:102:28)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```
I am looking for a graceful way to just exit the sql connection when done processing but not killing the nodejs app.
Let me know if i am not clear, i am trying to understand this module

**Comment by dougwilson** [comment]
Typically this error is because the TCP connection between your MySQL server and your Node.js app disappeared for some reason (network, firewall, MySQL server, something). As for preventing it from crashing your app, as is standard in Node.js land, you have to add `error` event listeners to certain things or errors emitting will by default crash your app.

The two main things you need to add error handlers are `pool`s you create with `createPool(...)` and `connection`s you create with `createConnection(...)`.

You can find more information in our section on error handling: https://github.com/felixge/node-mysql#error-handling

**Comment by amolkedar** [comment]
Thanks doug, yes i started using the connection pool and the app doesn't crash anymore
