### ISSUE TITLE
how can I to configure SSL flag when creating a connection?

### ISSUE THREAD

**Issue by zilev** [felixge/node-mysql#1178]
Will be something like this?, somebody can help me please?
```
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'me',
  password : 'secret',
  database : 'my_db',
  ssl: true
});
```

I'm having this error:
```
[Error: Server does not support secure connnection] stack: [Getter]
```

**Comment by dougwilson** [comment]
This error is because the MySQL server you are trying to connect to is not configured for SSL. You can read more about setting up your MySQL server for SSL connections in the MySQL manual here: https://dev.mysql.com/doc/refman/5.6/en/using-ssl-connections.html

**Comment by Zilev** [comment]
@dougwilson  thanks for helping me. I've already configured MySQL to Use SSL Connections as https://dev.mysql.com/doc/refman/5.6/en/using-ssl-connections.html, but the error continues, maybe is there other step after configure? thanks in advance :smile:

**Comment by dougwilson** [comment]
It's no problem! In order to use SSL, you cannot simply just do `ssl: true` :( You have to provide all the options, including the certificate in an object (more explained here: https://github.com/felixge/node-mysql#ssl-options).

Also, are you still getting the error "Server does not support secure connnection" or a different error? The error "Server does not support secure connnection" specifically means that your MySQL server itself is not correctly configured, rather than anything you are doing with this client.

**Comment by Zilev** [comment]
isn't there the possibility to only enable this flag? (ssl:true)  https://github.com/felixge/node-mysql#other-available-flags, without adding any certificate in an object?

**Comment by dougwilson** [comment]
It is not possible with how MySQL works. If you can determine a way, PRs are accepted!

Also, are you still getting the error "Server does not support secure connnection" or a different error? The error "Server does not support secure connnection" specifically means that your MySQL server itself is not correctly configured, rather than anything you are doing with this client.

**Comment by Zilev** [comment]
yeah I think the main problem is I'm continue using this
```
ssl: true
```
jejeje I'll change that and test again :smile:
thanks you so much for help!

**Comment by Zilev** [comment]
just a question more please, is not clear for me this flags https://github.com/felixge/node-mysql#other-available-flags, when and how can I use?. This way?
```
var connection = mysql.createConnection("mysql://localhost/test?flags=-FOUND_ROWS");
```
If I use SSL, what will the behavior?

**Comment by dougwilson** [comment]
If you need to use the flags, you can use them with that string format, but we recommend you use the object format so that all options are available to you:
```js
var connection = mysql.createConnection({
  database: 'test',
  flags: '-FOUND_ROWS'
})
```

**Comment by Zilev** [comment]
but what will do the flag SSL ?

**Comment by dougwilson** [comment]
Those flags are just listed because they are in the source code for the MySQL command line client as part of MySQL; they have no functionality in this module.

**Comment by Zilev** [comment]
ohhh now I get it :smile:  thanks
