### ISSUE TITLE
The problem is pool

### ISSUE THREAD

**Issue by 2byte** [felixge/node-mysql#1199]
```
for (i in [1,2,3,4,5,6,7,8,9,10]) {
    pool.query(igaccountsUpdateSql, [row.id], function (err, rows) {
                    if (err) throw err;
     });
}

pool.end();
```
Querys not execute. `pool.end();` fast close pool, then mysql error pool is closed.

**Comment by dougwilson** [comment]
Hi! This is a common problem when learning Node.js/event loop-based runtimes! You are actually calling `pool.end` too early, because you are not waiting for the calllback to run. You need to call `pool.end` after you have completed running your queries. A simple change to your example to do this would be the following:
```js
var cbs = 0;
for (i in [1,2,3,4,5,6,7,8,9,10]) {
    pool.query(igaccountsUpdateSql, [row.id], function (err, rows) {
                    cbs++;
                    if (cbs === 10) pool.end();
                    if (err) throw err;
     });
}
```
