### ISSUE TITLE
The problem is get bigInt from table

### ISSUE THREAD

**Issue by 2byte** [felixge/node-mysql#1200]
If do query to table with field bigInt, results fields with numbers will incorrect.

**Comment by dougwilson** [comment]
Hi! This is a common misunderstanding when first learning JavaScript :) So all numbers in JavaScript are IEEE 754 double precision floating point numbers. This means the biggest number JavaScript can represent without screwing it up is 9007199254740992:
```
$ node -pe '9007199254741011'
9007199254741012
```
You can see the Node.js console itself shows how a number is just wrong when converted into the internal JavaScript representation.

To get around this JavaScript langauge lilmitation, we provide two options in https://github.com/felixge/node-mysql#connection-options :

1. Set `supportBigNumbers: true` in your connection options. This will slow down your queries and return an object for the value from the `bignumber.js` library.
2. Set `bigNumberStrings: true` to just always get big numbers back as strings instead of JavaScript numbers.
