### ISSUE TITLE
Does mysql or node block the event loop?

### ISSUE THREAD

**Issue by McFarts** [felixge/node-mysql#1222]
Just curious because when I generate a shit ton of loot for my game and it shows up in the map, every player basically can click on it and it will run an insert query.

I am using innodb, and have really good innodb settings to allow for very fast insertion speeds.

My question is, let's say thousands of users start looting items... does mysql become the one that bottlenecks node right? This module just basically tells mysql to do it's job, right? If so, that means I would need to scale out my MYSQL if I am experiencing event loop issues, correct? Or will there never be an event loop issue with mysql as node just tells it to do it's job and free's up that particular event loop?

Or does the high insertion rates block the CPU... which then blocks node event loop? lol no idea.

**Comment by sidorares** [comment]
> Or will there never be an event loop issue
Any code in node.js blocks event loop, and events processed only after all your code finished. This driver does not do any complicated calculations - just parses incoming binary data and call callback functions with result.

you can use helper library like https://github.com/tj/node-blocked to measure event loop delays. One common source of delay is json parsing / serialising: for example, you query 1000s or rows  of data from mysql ( this does not block loop since data is read in many incoming packets after which code execution is handled back to event loop ) and after that you do `JSON.stringify(largeobject)` <- that's one single synchronous operation and might add some noticeable delay. I suggest to measure some real life usage numbers before optimising

**Comment by McFarts** [comment]
@sidorares  Alrighty, thank you for the expertise! So basically the only real world life way to block node using mysql is to get 1000 or so (or how many) and put that data through v8 code.  It looks like I would beable to handle a high amount of inserting than too, if t he data is only random numbers (player stats),  so I should be fine I think

**Comment by David-Turbert** [comment]
Have you try to disable trace with "trace" parameter. In my case it works on big column data more than 20Mb
