### ISSUE TITLE
Doubt: How to know the status of a connection?

### ISSUE THREAD

**Issue by jabrena** [felixge/node-mysql#1226]
I am using MySQL in an App and I would like to know if exist a method to know the status of the connection? something similar to isConnected()

Many thanks in advance

**Comment by dougwilson** [comment]
We listen to events from Node.js `net` library and the protocol and keep the `connection.state` property updated with this information, but, due to how TCP functions, the connection may have gone bad and Node.js's `net` library may not have informed us yet until we try to use it. Because of this, the only true way to know if a given connection is working is to use the `connection.ping(cb)` method (https://github.com/felixge/node-mysql#ping) to check.
