### ISSUE TITLE
Cannot use LAST_INSERT_ID

### ISSUE THREAD

**Issue by asendia** [felixge/node-mysql#1228]
```javascript
var query = "INSERT INTO students (user_name) VALUES ('Celty')";
query += "INSERT INTO books (student_id, title) VALUES ( LAST_INSERT_ID(), 'Secret Book' );";
```

Hi guys, somehow the query above returns parse error on c.query() while it works fine in mysql console. Did I miss something?

**Comment by dougwilson** [comment]
Hi @asendia , it looks like you are joining two queries together in a single string. In order to do this, you need to do two things:

1. You need to put a semicolon (`;`) between them in the string. Right now, you are missing a semicolon between the two queries.
2. You need to enable multi statements: https://github.com/felixge/node-mysql#multiple-statement-queries

**Comment by asendia** [comment]
@dougwilson I didn't know about enabling multi statements query, thanks a lot! (I did put ; in my actual code)

**Comment by dougwilson** [comment]
No problem!
