### ISSUE TITLE
PROTOCOL_SEQUENCE_TIMEOUT

### ISSUE THREAD

**Issue by StevePavlin** [felixge/node-mysql#1281]
Hi, I receive this error when my server runs overnight. I have the sql server running on a remote host if that helps.

**Comment by dougwilson** [comment]
Hi! Are you using the connection pooling or trying to maintain a single connect all night?

**Comment by StevePavlin** [comment]
Hi, I'm using a connection pool.

**Comment by jcq** [comment]
For the record, I just upgraded from Node 0.12 and am now getting this error on all of my connections. I've seen a few issues here (#1236, #1240, #1241, etc) that seem to describe the same issue that I'm having, but all seem to indicate that Node 4.2.1 should have fixed the problem. I'm running Node 4.2.2 on two servers and Node 5.0.0 on my local machine, and all are still getting PROTOCOL_SEQUENCE_TIMEOUT errors from code that worked perfectly under Node 0.12.

Is there another suggested solution for those of us already running latest Node?

**Comment by dougwilson** [comment]
Hi @jcq , the 4.2.1 issue is only specifically about the error "Handshake inactivity timeout"--all other errors have nothing to do with using the buggy Node.js 4.2.0 release. I would be happy to heal either of you two with this issue, but there is just not enough information here for me to be able to determine any kind of answer. Is there any additional information you can provide?

**Comment by intellent** [comment]
Hey guys,

I’m afraid, I can’t help, but provide more information, since I am running into the same problem but under different circumstances. I use connection pooling with the default configuration on a local machine where both MySQL (actually MariaDB) and the node processes are running.

I have two node applications. The API which uses node-mysql to access and deliver data and the actual app which accesses the API via REST.

So I initially start my API application, send it to the background and start another node process with the app. Everything works fine and I can access the database through the API. However once I stop both apps and try to restart the API, I get the following error from node-mysql:

    { [Error: Handshake inactivity timeout]
      code: 'PROTOCOL_SEQUENCE_TIMEOUT',
      fatal: true,
      timeout: 10000 }

After that happens, the error persists until I reboot the machine. Even a restart of MySQL itself doesn’t solve the problem. This only happens, when I run two node processes side-by-side. If I just run the API and stop it again, I can restart it without any errors. This seems really odd to me. Any ideas?

**Comment by jcq** [comment]
After further investigation, I determined that the issue I encountered was due to the combination of the newer versions of Node [including the updated OpenSSL with protections against Logjam](https://nodejs.org/en/blog/release/v0.12.5/) attacks (it now rejects handshakes w/ DH parameters shorter than 768 bits). 

Unfortunately, the MySQL server to which my code was connecting is managed by others, so I had to roll back to Node 0.12.4 for now until they complete the upgrade to a compatible version of MySQL. 

It just happened that the error that I encountered (PROTOCOL_SEQUENCE_TIMEOUT) after upgrading Node on the server in question was the same as those encountered by others after upgrading to Node 4.2.0, so I initially misunderstood the source of the error I encountered.

Anyhoo, feel free to disregard my part of this.  :)

**Comment by steirico** [comment]
Thanks @jcq for your investigations. I can confirm that PROTOCOL_SEQUENCE_TIMEOUT is related to the used cipher.

I got work around by specifying the cipher. To do so have a look at #1185.

A cipher that works for me with node 4.2.3 is 'AES256-SHA'.

**Comment by dougwilson** [comment]
Yea, not sure why Node.js decided to just disable it or whatever.
