### ISSUE TITLE
Transactions on single shared (non-pooled) connection- Safe?

### ISSUE THREAD

**Issue by bartonsprings** [felixge/node-mysql#1283]
Will the simple transaction example shown here: https://github.com/felixge/node-mysql#transactions work for a single db connection shared across the application where multiple http requests could be going on in parallel, contending for database access (using async library also).

I am worried that connection may not be held through the entire transaction and due to async nature of Nodejs some other request will take the time slice in between and use the connection before the transaction is complete, which could result in messed up rollbacks and commits on same single connection. 

So is it safe to use the transactions on single shared (non-pooled) connection? Thanks in advance.

**Comment by dougwilson** [comment]
Hi @bartonsprings ! What you are describing is dangerously unsafe. If you are using transactions, you cannot use only a single connection to act on those transactions in parallel. Effectively, you need to create one connection per logical transaction (likely, per request) and make sure to keep each request's queries isolated to it's own connection. This is because of the way any event-loop-based system (like Node.js) functions. I hope that helps!

**Comment by bartonsprings** [comment]
Thanks Doug. I kind of was already assuming that is the case for
transactions.

I am now using connection from a pool (using getconnection) and then using
it for specific transaction. So if there are multiple transactions going
on, they will each get their own connection and the respective connections
will be released after transaction is completed.

When you say that I should use it per request. Can you help me what does
that mean? Do I have keep track of every http request in my express
application? For non transactional queries I am using a single and same
connection across the express application without the pool. This would be
shared across multiple requests. Is that unsafe too?

Thanks,

**Comment by dougwilson** [comment]
> I am now using connection from a pool (using getconnection) and then using it for specific transaction. So if there are multiple transactions going on, they will each get their own connection and the respective connections will be released after transaction is completed.

This description sounds like the right way to do it, if that helps :)

> For non transactional queries I am using a single and same connection across the express application without the pool. This would be shared across multiple requests. Is that unsafe too?

It is unsafe, yes, depending on what you are doing in your queries. If you call any MySQL function that depends on the result of a previous query (think `LAST_INSERT_ID()` or `ROW_COUNT()`), then you may not get the value you expected due to a non-related query going between the two queries from the connection sharing. Same for if you are using any variables to store/retrieve data.

**Comment by bartonsprings** [comment]
Oh! I did not realize this aspect. Thanks a bunch for alerting me on this aspect. I need to change my design to use separate connections for every query based on this information. Your example above clarifies it and yes, I am using the intermediate variables like Insert_id etc returned from previous queries in non-transaction based queries. 
Looks like that the changes will be more involved and verbose code but "safer". Basically what this means is that it comes down to using separate connections (using get connection from pool) for any query being executed irrespective of transactions. Thank you very much for your response and help. Really appreciated.

**Comment by dougwilson** [comment]
No problem!
