### ISSUE TITLE
ER_KEY_COLUMN_DOES_NOT_EXITS?

### ISSUE THREAD

**Issue by benderTheCrime** [felixge/node-mysql#1306]
It looks like `ER_KEY_COLUMN_DOES_NOT_EXITS` should be `ER_KEY_COLUMN_DOES_NOT_EXIST` perhaps in `lib/protocol/constants/errors.js`

**Comment by dougwilson** [comment]
Hi! Thanks for the report. Unfortinately that is not something we can change; those codes come directly from the MySQL server source code. Perhaps report the error to MySQL server itself and when they release a new version, we'll just pull in the updated code name.

MySQL server even documents the code as "ER_KEY_COLUMN_DOES_NOT_EXITS" in their own documentation: https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html so I can only assume it is intentional. Our code have to match the MySQL documentation to make sense.
