### ISSUE TITLE
Prefix when using CONCAT?

### ISSUE THREAD

**Issue by articho** [felixge/node-mysql#1312]
Is it possible to use nestTables=true with CONCAT and GROUP_CONCAT selects?

Using nestTables=true gives these results:
```
"": {
    //results from CONCAT and GROUP_CONCAT
},
table1: {
    //results
},
table2: {
    //results
}
```

Kindly,
Mathieu

**Comment by dougwilson** [comment]
Hi! Unfortunately there is no way to do it currently. The way the nest tables option works is that it uses the field and table information provided by the MySQL server. If any column is a calculated column, the table name always comes back from your MySQL server as an empty string, so that's what we group it as. This is a shortcoming of the MySQL protocol itself.
