### ISSUE TITLE
Question: Connection Pool

### ISSUE THREAD

**Issue by JoelV** [felixge/node-mysql#1314]
Scenario: I'm using connection pool to connect to the database with a connectionLimit set to 10. During the day the pool only ever uses 5 simultaneous connections and thus they are 5 open connections in the pool. 

Question: Will node-mysql always keep those 5 connections alive or do they close after a period of time of inactivity?

**Comment by dougwilson** [comment]
Hi @JoelV ! So the way this module handles idling connections is that it just leaves them there to idle (as in, this module does no active keep-alives). When ever you call `pool.getConnection`, this module will check if it is up by sending a ping packet. If it works, you get that connection back, otherwise it will automatically create a new connection.

This mechanism allows for minimal network traffic, and of course you can always build active keep-alives on top of this module if you wish.

I hope this helps!

**Comment by guypaskar** [comment]
Wouldn't this be a bit intrusive?

i.e I'm using a 2 pools with 200 connections each.
I see I have about 240 connection in the db which are in sleep mode. It looks like it makes the db really slow.

What may be the cause to that?
