### ISSUE TITLE
Query queued but not executing

### ISSUE THREAD

**Issue by admin4life** [felixge/node-mysql#1315]
I have an issue posted on [stack overflow](http://stackoverflow.com/questions/34444720/node-mysql-queries-queue-but-never-execute)
I have hundreds of thousands of binary files i'm processing. I process a group of files by directory and then try and insert the processed results into mysql. I have tried at least 50 different ways to try and force the con.query to execute but it just queues the query and never executes until the entire script is done processing. The problem is if I let the queue build up that long then I hit the mem limit. I don't think this is an issue with the mysql lib but I'm so stuck I don't know what else to do and my ocd wont let me sleep till I understand what the issue is.

**Comment by dougwilson** [comment]
Hi @admin4life , I may be able to give you a more through answer if you posted some code, but from your description here and on stack overflow, the reason you are experiencing this is because you are not using Node.js asynchronous programming correctly.

You see, in Node.js, all networking tasks are async-only tasks. When you combine this with sync file tasks, you end up just queuing all your queries until you stop doing your sync file tasks and the Node.js core networking libraries has a chance to callback into this library with the network socket.

You need to change all your file tasks to be async.
