### ISSUE TITLE
Uncaught TypeError: Net.createConnection is not a function

### ISSUE THREAD

**Issue by jkruse14** [felixge/node-mysql#1323]
It seem that the Net object is empty when creating a connection:
    
    // Connect either via a UNIX domain socket or a TCP socket.
    this._socket = (this.config.socketPath)
    ? Net.createConnection(this.config.socketPath)
    : Net.createConnection(this.config.port, this.config.host); //error is here, Net returns Object{} in console

I am using the example code:
```js
var connection = mysql.createConnection({
    host     : 'localhost',
    user     : 'me',
    password : 'pwd',
    database : 'example',
    port: '3306',
    debug:true
    });
		 
    connection.connect(function(err){
        if(err) {
            console.log('error connecting: ' + err.stack);
    	    return;
	}
    });
    connection.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
        if (err) throw err;
        console.log('The solution is: ', rows[0].solution);
    });

    connection.end();
```
Am I missing a dependency? Please let me know what other information I can provide, thanks!

**Comment by dougwilson** [comment]
Hi! There is no dependency you are missing, as `net` is a core part of Node.js itself. If it is coming up as an empty object, there are only a few things that can do this:

1. You are not running on Node.js. You must run this module on Node.js only; you cannot run it in a web browser, mobile phone, or other similar environments.
2. You are running this module through browserify, webpack, or something similar. Don't do that.

If none of the above apply to you, then I need more information in order to help. Can you please give complete details of exactly how you are running withe above script, including all commands you are running?

**Comment by jkruse14** [comment]
Ah, well there it is. I am running this through webpack in the browser. Sorry, I'm brand new to Node.js!

**Comment by dougwilson** [comment]
It's no problem! I'm glad that turned out to be the issue.

I took a look and it looks like when building for the web browser, those packers will basically make any `require('net')` return the empty object `{}`, which is where the issue comes from. The reason for this is because they don't (yet?) support emulation of the `net` module (as in raw sockets) from the web browser.
