### ISSUE TITLE
Provide the option to Rename Column names.

### ISSUE THREAD

**Issue by sai070cm118** [felixge/node-mysql#1328]
This is not an issue. It's an suggestion for add as feature list for MySql module. In most of the Restful service the developer think not to return the actual table column names.

At present For this the returned object need to be Restructure with custom column names and sent as response. so, That I am posting this.

**Comment by dougwilson** [comment]
Hi! Are you not able to use the SQL "AS" operator to rename the columns? As this is a low-level driver only, you have two options to rename the columns in the resulting object:

1. Use your SQL to return the column names you want. This is the "AS" operator in SQL (not documented here, because documenting SQL it outside the scope of the driver).
2. Create a wrapper around this driver that provides the renaming functionality in JavaScript.
