### ISSUE TITLE
Error "No connections available" (Pool's config.waitForConnections == false) has no properties err.code and err.fatal

### ISSUE THREAD

**Issue by mxscho** [felixge/node-mysql#1332]
Hi,

The documentation says that every error thrown or passed to a callback contains the two properties `err.code` and `err.fatal` (see [here](https://github.com/felixge/node-mysql#error-handling)).
However, the "No connections available" error that gets passed to the `Pool.getConnection` callback [here](https://github.com/felixge/node-mysql/blob/master/lib/Pool.js#L65) if `config.waitForConnections` is `false` does not contain these properties.
Is this by design because this error is not associated with a connection? So far I haven't found any other errors which also do not contain the properties. But if so, just close this issue.
Otherwise I would suggest adding these properties to this error and think of a new error code/name for this exception.

Thank you

**Comment by dougwilson** [comment]
Hi @mxscho , it looks like the documentation is just not clear enough :) So the `err.fatal` property only exists if we have a reason to set it (typically when `true`), because `undefined` is a falsy value in JavaScript. That error is not a fatal error from a protocol standpoint (remember, this is a low-level driver module, so many operations are in the context of the protocol).

The `code` property we document, but I guess it's not technically on all error objects, since things like `TypeError`s and other control-flow errors just won't have them in Node.js land. I'll update the documentation to better specify these kinds of things.

**Comment by mxscho** [comment]
Even though I'm quite new to the Node.js stuff, you gave me a detailed explanation for the behavior. I appriciate that - thank you very much.
The first thing about `err.fatal` does absolutely make sense.
I'm actually really pleased with the way errors are handled (and need to be captured) in this driver so I thought that this one is a mistake. Actually I should've looked around more and I would've found out that various other (control-flow-related, as you said) stuff like e.g. "Pool is closed" does also not contain an `err.code` property.

I stumbled upon this while trying to implement a specific control flow if all connections are in use and I didn't want to use `if (err.message == "No connections available.") { ... }` because I thought it's not a good way to check a message which might be altered some time in the future (I thought that's what codes are there for). But obviously this thoughts do not really belong to an issue section so I'm quite ok with how it's currently implemented.

**Comment by dougwilson** [comment]
Right, makes sense. I can add a code to that error as well as update the documentation. You can use the message (and I hesitate to change messages because a lot of the time you have to use them; Perl has the same kind of problem), but using a code that is less likely to change is better in the long run.
