### ISSUE TITLE
Cannot override machine hostname added to user

### ISSUE THREAD

**Issue by diginfo** [felixge/node-mysql#1358]
The system is adding the machine hostname to the userid when making a connection and I seem to be unable to override this.

As you can see, the machine's HOSTNAME has been prepended to the user ID and this is causing connection refused due to MYHOST not having priveledges, even though I am connecting locally to the database.

I cannot override this by setting the user to root@localhost.

	var db = mysql.createConnection({
	  host : '192.168.42.75',
	  user : 'root',
	  password : 'bukit8002',
	  database : 'mysql',
	  debug: false  
	})

	{ [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'MYHOST' (using password: YES)]
	  code: 'ER_ACCESS_DENIED_ERROR',
	  errno: 1045,
	  sqlState: '28000',
	  fatal: true 
	}

**Comment by dougwilson** [comment]
Hi! Sorry if the way MySQL works is a little confusing, but this is just part of the MySQL grant system. This module is not sending your hostname (you can use something like Wireshark to verify this) to the MySQL server, rather your MySQL server is doing a reverse DNS on the IP address used to connect to it and uses that in the grant system.

The reason MySQL is seeing your hostname is because you are connecting using your external IP address. You should use the loopback address `127.0.0.1` for your MySQL server to resolve the connection as coming from `localhost`.
