### ISSUE TITLE
Is corruption possible when using pools ?

### ISSUE THREAD

**Issue by tempo22** [felixge/node-mysql#1369]
Hi,

I'm working a small app that will process a lot of small queries: around 200 requests per seconds, each one making a select followed by an update.
I found this module pretty much capable of this when using the pools but i'm now concerned of what happen if something goes wrong.

Coming from PHP, i know that persistent connection can bring some problems ( [cf this post](http://stackoverflow.com/questions/3332074/what-are-the-disadvantages-of-using-persistent-connection-in-pdo?answertab=votes#tab-top) ) and i would like to make sure this will not happen with this app.

**Comment by monken** [comment]
Persistent connections are the only way your application will scale. Opening one connection per request, as mentioned by the cf post, will let you run into the maximum connections limit of the database.
The problems he mentions are very real if you don't know how to clean up after yourself. Wrap everything in transactions that modifies rows (especially your SELECT / UPDATE procedure). This ensures consistency. Make sure you `release` the connection back to the pool. Capture all exceptions and handle them properly. Personally, I prefer using Promises over the callback syntax. It makes life much easier when it comes to handling complex code paths.

**Comment by dougwilson** [comment]
Hi @tempo22, in addition to what @monken said, something else you can do to help is if the first thing you do in your code after the `.getConnection()` is `.changeUser()`, that will ensure that the session is clear of any pending transactions if you do not trust your code is handling error conditions fully. This will definitely slow down your overall speed, though, as `.changeUser()` is a pretty heavy function that does everything creating a new connection does but without creating a new TCP connection.

I would recommend just properly handling error conditions in the code as @monken says :) The biggest different between the pool here and persistent connections in PHP is that if your script dies in Node.js, the entire thing, even the pool is killed. This is very different from what happens if your PHP script dies, since the persistent connections are managed by the persistent runtime, which does not crash with your script.
