### ISSUE TITLE
how can I use @User-Defined Variables

### ISSUE THREAD

**Issue by hamsuu** [felixge/node-mysql#1373]
```js
connection.query('SELECT @rownum:=@rownum+1 FROM TABLE WHERE (@rownum:=0)=0  ', function (err, rows) {
        if (err) {
            console.log('err while Select: ' + err);
            throw err;
        }
        console.log(JSON.stringify(rows));
        connection.end();
    });
```
result: `@rownum:=@rownum+1 = null`
It seems like `@rownum` dosen't work..

I want to use mysql variables for subquery.
( ex> `SELECT * FROM ( SELECT FLOOR(((@ROWNUM:=@ROWNUM+1)-1) / 10 +1) page, A.*  FROM TABLE A WHERE (@ROWNUM:=0)=0 ORDER BY A.INDEX DESC ) B WHERE B.page = 1` )

Does anyone have any idea?

**Comment by dougwilson** [comment]
Hi @hamsuu, all this module does is send the text of your query to your MySQL server to process; having variables or not makes no difference to this module in any way.

As far as I can tell, at least for how you are trying to initialize the `@rownum` variable. Stackoverflow questions like http://stackoverflow.com/questions/8509996/is-there-a-way-to-get-the-row-number-in-mysql-like-the-rownum-in-oracle may help, otherwise I would suggest asking on Stackoverflow how to implement what you are trying to do in SQL.
