### ISSUE TITLE
Inconsistent conversion of Date fields when timezones are used

### ISSUE THREAD

**Issue by emptyemail** [felixge/node-mysql#1374]
Currently all date type fields (DATE, DATETIME, TIMESTAMP, etc...) Are parsed the same way. However if timezone parameter is configured on the connection, the types without a time component are getting converted into a local timezone the same way as types with a time component

```
      if (field.type === Types.DATE) {
        dateString += ' 00:00:00';
      }
      if (timeZone !== 'local') {
        dateString += ' ' + timeZone;
      }
      dt = new Date(dateString);
```

This shifts dates by by one day in locations that have a negative timezone offset. If a field of type DATE has 12/31/2000 in it, I would imaging it should be retrieved as 12/31/2000 regardless of which timezone your server is in or which timezone you have configured.

**Comment by dougwilson** [comment]
What is your proposed solution? JavaScript `Date` object require a time component, and as such, we parse the date as if it is midnight in the given timezone you choose. How does this shift the date? Can you provide a code example?

**Comment by emptyemail** [comment]
I realized I left out an important component, the timezone on the client system must be different from the timezone configured on the connection.

Here is the configuration that I have:

DB Server Timezone: UTC
Connection Timezone: UTC
Client Timezone: EDT

The solution for me was simple, to only add timezone component for non-DATE types, which would force the date to be parsed in local timezone preventing the shift.

```
      if (field.type === Types.DATE) {
        dateString += ' 00:00:00';
      } else if (timeZone !== 'local') {
        dateString += ' ' + timeZone;
      }
      dt = new Date(dateString);
```

example of shift with the original code:
```
      process.env.TZ === 'EST5EDT'
      timezone = 'UTC'
      dateString = '01/0/1/2000'
    
      if (field.type === Types.DATE) {
        dateString += ' 00:00:00';
      }
      if (timeZone !== 'local') {
        dateString += ' ' + timeZone;
      }
      dt = new Date(dateString);

      dt is now 12/31/1999 19:00:00 EDT
```

**Comment by dougwilson** [comment]
Sure, but now the times in the `Date` objects do not make sense, as they do not correspond to the same midnight as the other date/times that are set to midnight. The decision was that to construct a JavaScript `Date` object, we have to provide a time component, and this should make a server datetime of 2016-01-02 12:00:00 AM result in the exact same `Date` object as a server date of 2016-01-02.

If you need different customization, you can use the date strings options or provide your own type cast that only changes the `DATE` behavior.

**Comment by macias** [comment]
I just encountered the same problem with way DATE is treated. The date knows nothing about timezone so it should not be mixed with it (when I tell you my birthday is "1980-01-01" you don't ask in which timezone). Otherwise you will get datetime with non-zero time, which then in the process will be converted again to some other timezone and you lose or gain one day.

So I would opt for really sticking with treating DATE (mysql type) as well, date. The best we can do in JS is to use datetime with zero time part. And it is an easy fix:

The original code from RowDataPacket:

```
      if (field.type === Types.DATE) {
        dateString += ' 00:00:00';
      }

      if (timeZone !== 'local') {
        dateString += ' ' + timeZone;
      }

```

As you can see timezone is applied even for "DATE" fields. Suggested fix:

```
      if (field.type === Types.DATE) {
        dateString += ' 00:00:00.000Z';
      }
      else if (timeZone !== 'local') {
        dateString += ' ' + timeZone;
      }
```

So if it is a DATE make time part zero, because it is a date.

Please reconsider reopening this issue and changing the behaviour -- thank you in advance.
