### ISSUE TITLE
Application access to mysql error codes and numbers

### ISSUE THREAD

**Issue by p-somers** [felixge/node-mysql#1378]
When an error is passed to a callback, is there any way of checking for specific codes without needing to hardcode or come up with my own list of error codes? Since this module already has one (/lib/protocol/constants/errors.js), it would be nice not to have to do that redundantly, but I can't figure out how to access them.

It would be nice to do something like this:
if (error) {
   if (error.errno === mysql.errors.ER_DUP_ENTRY) {
        ...
    }
}

**Comment by dougwilson** [comment]
error.code === 'ER_DUP_ENTRY'

**Comment by p-somers** [comment]
Still a hard coded string though...

**Comment by dougwilson** [comment]
And the property name is also a hard coded string, just in the form of a property name. Spelling it wrong will result in no errors. Using err.code is the standard in the Node.js core, which we follow.

If you have a different way,please feel free to open a PR and elaborate on the specifics in why it is better, and we can absolutely consider changing it, if we can understand why.

Otherwise, Node.js allows you to require any file in a module you want:

    require('mysql/lib/protocol/constants/errors')
