### ISSUE TITLE
the result of poolCluster.of() 

### ISSUE THREAD

**Issue by bjshijh** [felixge/node-mysql#1384]
the result of poolCluster.of() is different from the result of mysql.createPool(). 
this always course confusion. 
Why  not make them the same?
thanks

**Comment by dougwilson** [comment]
Hi @bjshijh, the entire pool cluster system was a community contribution, which certainly has some oddities (for example, it came with almos no documentation).

From what I know of the pool cluster is does not return the same object because it's return object actually can consist of multiple pool objects. For example, if you have a cluster of 5 pools and call `.of('*')`, we cannot return the same object as `mysql.createPool()` because we have to return an object that can actually aggregate all those pools together, including with the necessary logic for fail over and balancing.

Do you have any suggestions on how to solve this? If the result of `.of()` made sense to provide that pool object, it would do that, but it currently is returning an object that is much more complex than that. If you think it will help, always feel free to even provide suggestions via. a pull request.

**Comment by dougwilson** [comment]
Hi @bjshijh, I hope the information has helped you! I didn't hear back with any suggestions in over a month, so closing the issue for now.
