### ISSUE TITLE
same as #1223

### ISSUE THREAD

**Issue by qarl** [felixge/node-mysql#1403]
I've got the same problem as #1223, but it's been closed and locked so i can't comment on it there.

I'm running node 4.2.0 on aws lambda, just like everyone else.

**Comment by dougwilson** [comment]
Hi @qarl, since that issue, nothing has changed. As I said in that ticket:

> I'm not able to reproduce, so without a way to reproduce the issue, there isn't much I can look into successfully. I can poke around at the code here, but it may not ever turn up anything of use. If you could debug your code and determine what is happening and issue up a PR, that's likely the best course of action :)

There is nothing I can do, you have not provide any additional information outside that issue, either. Please debug the issue and provide a PR with the fix.

**Comment by qarl** [comment]
Sure.  But I thought it was important to speak-up and say "this problem still exists."

But since the comments are locked on that issue, I was forced to create a new issue.  And I'm somewhat curious as to why you'd lock the comments on an unsolved problem.  (Never mind closing it.  Presumably you have a different definition of "closed" than I do.)

**Comment by dougwilson** [comment]
Everyone confirmed that a new version of node.js worked. We can not do anything about bugs in node.js 4.2.0. Have you tried a newer version of node.js?

**Comment by qarl** [comment]
AWS lambda doesn't support newer versions.  That's why everyone continues to have the problem.

Perhaps if you hadn't locked the comments on the other issue, someone would have told you about this before now.  Again, I remain curious about that decision.

**Comment by dougwilson** [comment]
> And I'm somewhat curious as to why you'd lock the comments on an unsolved problem.

The problem is resolved. It is a bug in Node.js 4.2.0 that Node.js has fixed. Don't use that version. I don't know what more you think we can do.

> Presumably you have a different definition of "closed" than I do.

I close issues where no information is provide, like you provide no information to reproduce the issue, no information on what version of this module you are using. Literally no new information from that other ticket.opening 'me too" issues with no helpful information will promptly be closed, as keeping them hoping will just mean they are open indefinitely.

**Comment by dougwilson** [comment]
I locked this issue because you are pissing me off and clearly you don't understand that Node.Js released a buggy version of Node.js. There is nothing we can do besides cripple our module to not use features that are broken in 4.2.0. Software has bugs, get over it. Complain to AWS to at least provide a version of Node.js that is even supported by the Node.js foundation. They fixed the bug as soon as it was found and released a fix.l, so use it.
