### ISSUE TITLE
Continuation of #1403

### ISSUE THREAD

**Issue by qarl** [felixge/node-mysql#1404]
On the contrary, "me too" is valuable information.  As I already explained, it informs you that your users are still experiencing a problem.

I am truly sorry my saying "this is still broken" has made you angry.  You might want to consider that, and why you feel the need to silence people you disagree with.

**Comment by dougwilson** [comment]
Like I said over and over: this is a bug in Node.js 4.2.0. The bug was fixed and a 4.2.1 was released. There is nothing we can do. Node.js is not some magic thing that can never have bugs.

**Comment by qarl** [comment]
> There is nothing we can do.

Actually, there is something you can do.  If you discover that many of your users are suffering from this problem, you could find a workaround (perhaps use a different timeout mechanism, or some such.)  This is common in software development; I'm surprised you're unaware of it.

> Node.js is not some magic thing that can never have bugs.

Strawman arguments are typically unhelpful, also.  But I do congratulate you for not locking the comments here - that was the right choice.

Best -

K.

**Comment by dougwilson** [comment]
> If you discover that many of your users are suffering from this problem, you could find a workaround (perhaps use a different timeout mechanism, or some such.) This is common in software development; I'm surprised you're unaware of it.

Since this bug was from last year, I don't remember all the details, but I believe this was looked into and we couldn't figure out a work-around. If you know a work-around, please provide a pull request. No one else has provided a pull request, either, so perhaps you know something no one else knows, and you can educate us with a lovely pull request. If not, go fuck yourself.

**Comment by dougwilson** [comment]
I locked this issue again because you show that you just walk in here feeling entitled and not even understanding the history of these issues. If we know how to work on Node.js 4.2.0, we would. This module fucking supports Node.js 0.6 for God's sake. Why do you think that is? It is because users wanted it over and over and then we figured out how to provide it. On the 4.2.0 issue, we dug in and as far as I remember, there was no good fix. If you believe there is a fix, provide it, otherwise you are only making noise here.

You are not entitled to anything from an open source project. I'll in fact unlock this issue for one last offer: if you pay me $1,000 (US) (we can even use a third-party to hold the money between us to make sure both sides hold up on the promise) I will spend all my time fixing this module to work on node.js 4.2.0. If you would like to save that money, that's simple: either accept that we have already spent a ot of time looking into this issue and you just have to use a different version of Node.js or provide a pull request to add support for Node.js 4.2.0

**Comment by dougwilson** [comment]
Here are two more solutions as well: use a different MySQL module or wait for Oracle to provide a MySQL module for Node.js so unofficial modules like this are not necessary and you can get support you would expect from a company.

**Comment by qarl** [comment]
Silencing dissent is childish, friend.  Take care.
