### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by kudo070** [felixge/node-mysql#1407]
```
 connection.query("SELECT * FROM `case` WHERE `id` !=0 AND `status` =1", function (err, rows) {

            for (num = 0; num < count(rows); num++) {
                connection.query("SELECT count(*) FROM `items` WHERE `price` > " + rows[num].price + " AND `counts` >0 ", function (err, item) {
                    console.log(num);
                    rows[num].counstitem = item[0]['count(*)'];
                    console.log(rows[1]);
                });
            }
        }
    );
```

TypeError: Cannot set property 'counstitem' of undefined

**Comment by kai-koch** [comment]
If you have ```10``` results in the outer query at the time the inner Query is executed ```num``` equals ```10```. (Last increment of ```num``` after the last element of ```rows``` array.)
```rows[10]``` is ```undefined```. (the last defined item would be ```rows[9]``` because the counting arrays start at ```0```)

Please consult google for some tutorials on "asyncron programing in Node.js" and why it is a very bad idea to "declare anonymous function inside a for-loop", especially if the function is used as "asyncron callback" and how outer count-variables are referenced in the "declaration of inner anonymous functions". 

Closed. Not an node-mysql issue.
