### ISSUE TITLE
Table field's `NOT NULL` constraint error is not raised

### ISSUE THREAD

**Issue by fictiousfido** [felixge/node-mysql#1413]
We are experiencing some unexpected behaviour when running insert queries. The particular case is that when we do not specify a (field_name, value) pair for a field with a `NOT NULL` constraint no error is raised and instead an empty string is inserted. Unfortunately I cannot find where this occurs or a flag to stop this behaviour. Any help would be appreciated.

OS environment: Mac OS X 10.11.4
node version: v0.12.7
node-mysql version: 2.8.0
mysql version: Ver 14.14 Distrib 5.6.25

Example Table definition:
```
CREATE TABLE IF NOT EXISTS faketable (
    field_one             VARCHAR(64)   NOT NULL    COMMENT 'A field which cannot be NULL',
    field_two             VARCHAR(64)   NOT NULL    COMMENT 'A second field which cannot be NULL'
)
COMMENT 'A fake table to explain mysql client issue.'
DEFAULT CHARACTER SET utf8
COLLATE utf8_bin
ENGINE InnoDB;
```

Unittest setup ensures that there is an empty database table with the basic node-mysql client connection.
For example:
```
mySqlClient = mysql.createConnection({
                host: host,
                user: username,
                password: password,
                database: db,
                multipleStatements: true,
                debug: true
            });
mySqlClient.connect();
```

Example unittest which we expect to fail due to `NOT NULL` constraint. However, no error is raised and an empty string is inserted in the table.
```
it('Fails for inserting entry without field_two value', function(done) {
	// Test parameters
	var fieldOne = 'field one value';

	// We expect that if no value for `field_two` is given then the insert query fails due to `NOT NULL` constraint.
	var insertValues = {
		field_one: fieldOne
	};
	var insertQuery = 'INSERT INTO faketable SET ?';

	mySqlClient.query(insertQuery, insertValues, function queryCallback(insertError, result) {
		if (insertError) {
			return done(insertError);
	    }

	    // If no insertError is raised then we fail the test.
	    chai.assertEqual(true, false);
	    done();
	 });
});
```

The debugging output highlights that there was a warningCount of 1 but nothing further.
```
--> ComQueryPacket
{ command: 3,
  sql: 'INSERT INTO faketable SET `field_one` = \'field one value\'' }

<-- OkPacket
{ fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 1,
  message: '',
  protocol41: true,
  changedRows: 0 }
```

**Comment by dougwilson** [comment]
This is because in MySQL, that is not an error. MySQL is extremely forgiving. MySQL does raise a warning, though, and you can enumerate the warnings using `SHOW WARNINGS` as a query.

More information about how MySQL itself works can be found in the MySQL manual: http://dev.mysql.com/doc/

There are various strict modes you can enable on your MySQL session using queries that can alter that behavior (and I think you may be able to set them as server defaults too). More information about SQL server modes can be found in the MySQL manual: http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

I hope this helps! Sorry I don't have any good answers for you, other than that this is not an issue with the driver, only perhaps an understanding of MySQL server, which is super quirky!
