### ISSUE TITLE
Pool leaking connections if the current connection is busy

### ISSUE THREAD

**Issue by karhuton** [felixge/node-mysql#1426]
I'm using node async module to run 10+ queries in parallel (with additional crunching in node) and then waiting for all of them to finish until I render a html page in express. I'm trying to limit the number of db connections I open with pooling.

My problem is that node-mysql doesn't always obey connectionLimit and will open multiple connections never the less (as evidenced by manually keeping track with on('connection') and ending up with a mysql server that blocks connections after 10 is reached).

Here's how I'm using node-myqsl:

```
var mysql =  require('mysql').createPool(...)
var async = require('async')
...
exports.default = function(req, res, next) {
  async.parallel([ function(){
    mysql.query("....")
  }, ...], function(err, res) {
    res.json(...)
  }
}

```

How node-mysql doesn't leak connections:
1. start server
2. open page - wait till it's rendered
3. refresh page 10 times - wait each to render nicely

How node-mysql leaks connections:
1. start server
2. refresh page 10 times in few seconds (none of the loads finish)
-> opens up new connections until db returns ER_USER_LIMIT_REACHED

**Comment by dougwilson** [comment]
Hi @karhuton, thanks for the report! I need full, complete code I can use to reproduce the issue, otherwise there is nothing I can do. Since you can reproduce, you are in the key position to attach a debugger to diagnose the issue and come up with a solution. If you are looking for us to debug the issue, we need all of the following to proceed:

1. The version of Node.js you are using.
2. The version of this module you are using.
3. Provide complete server-side code that reproduces the issue. It must be self-contained such that I can copy and paste the code into a file and run it to have a server that reproduces the issue. Please use as few other modules besides this one as possible in order to reproduce the issue, as the more there are, the harder it is going to be to diagnose.
4. Provide the exact steps needed to reproduce the issue. For example, this may be a `cURL` or similar command to make to the server provided in number 3. Explain what we will see when we hit the issue and what we should see if the issue wasn't there.

**Comment by karhuton** [comment]
@dougwilson Ok, sorry for the report. I'll go look somewhere else for help.

**Comment by dougwilson** [comment]
Hi @karhuton, it's perfectly fine to report this. Perhaps this is a better question: what are you expecting me to do with this report? Obviously if the issue was straight-forward just from a description, we could just fix it, but as far as I can tell, we are obeying the `connectionLimit`. We are happy to dig in, but we actually need enough information to be able to do that.

If you are unwilling to provide basic information for us to reproduce, then there is nothing we can do. Alternatively, you can provide a bounty on this issue, and I will dig in deeper without you providing reproduction steps.
