### ISSUE TITLE
Error with nested queries

### ISSUE THREAD

**Issue by Piero87** [felixge/node-mysql#1427]
I'm trying to execute this query:

```js
mysql.query('SELECT R.*,K.name as key_name FROM rules as R, topics as T, table_keys as K WHERE T.id = R.id_topic AND T.type = "publish" AND K.id = R.id_key AND T.name = ?',topic, function (error, results, fields) {
	    
	    results.forEach(function(row){

                        mysql.query('SELECT T.name as topic_name_result, K.name as key_name_result FROM topics as T, table_keys as K WHERE T.id = ? AND K.id = ?',row['id_topic_result'],row['id_key_result'], function (error_2, results_2, fields_2) {
});
});
});
```

but i get this error when the nested query is executed:

```
/var/www/html/tesi-iot.com/public_html/nodejs_iot/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
              ^
TypeError: Object 14 has no method 'apply'
```
what is the problem?

thanks

**Comment by dougwilson** [comment]
Hi @Piero87, the issue is with some code you put in your callback, not with this module. The error you are getting, `TypeError: Object 14 has no method 'apply'`, means that you are probably doing `variable.apply(...)` somewhere and `variable` is the number `14` or something.

You didn't include any of your code that is in the callback function, so I can't pick out where this would be happening. Typically there is a much longer stack trace than the one you pasted which would point to were in your code this is occurring.
