### ISSUE TITLE
how to know whether the pool is available

### ISSUE THREAD

**Issue by willin** [felixge/node-mysql#1428]
https://github.com/WulianCC/node-wulian-mysql/blob/master/src/pool.js

sometimes query will go to be always hanging on, but no `err` was passed to `logger`

i guess maybe the pool is not useable any more.

how to confirm that the pool is ok, and how to recreate a pool?

**Comment by dougwilson** [comment]
Hi @willin, the pool is a general computer programming construct, and there is no such thing as the pool going bad. There can be cases where you check out connections from the pool and then never release them back, ending up in a situation where all connections are in-use and you can't get a connection from the pool, though.

You could probably add `debug('wulian:mysql:release')` to https://github.com/WulianCC/node-wulian-mysql/blob/master/src/pool.js#L51 and https://github.com/WulianCC/node-wulian-mysql/blob/master/src/pool.js#L43 to see if you have an equal number of queries to releases.

Otherwise, I would answer your question with "you never have to recreate a pool", and if you feel like you need to, there there are two possibilities:

1) You are not always releasing the connections you acquired back into the pool.
2) You found an unknown bug and it would be great to get more details on this.

**Comment by willin** [comment]
https://github.com/WulianCC/node-wulian-mysql/blob/master/examples/pool.js

Here's a test, why it can query again after the connection is already released?

**Comment by dougwilson** [comment]
> why it can query again after the connection is already released?

Because you still have a reference to the connection. The same object is handed out every time (which is the typical way a pool construct is done). You'll find the same behavior in generic pool modules like https://github.com/coopernurse/node-pool as well. You have to program your code not to perform queries after you programmed it to release it back into the pool.

**Comment by willin** [comment]
thanks for your patient.

```js
import mysql from 'mysql';
import debug from 'debug';
import {md5, getDefer} from 'wulian-common';
import {Pool} from 'generic-pool';

const db = {};
/**
 * 创建连接池
 * @param  {obj} options MySQL连接参数
 * @return {obj} MySQL Pool
 */
/* eslint no-console: 0 */
module.exports = async function createPool(options, logger = console.log) {
  const key = md5(JSON.stringify(options));
  if (!db[key]) {
    db[key] = new Pool({
      name: 'mysql',
      create: (callback) => {
        const c = mysql.createConnection(options);
        // parameter order: err, resource
        callback(null, c);
      },
      destroy: (client) => { client.end(); },
      max: options.connectionLimit || 10,
      // optional. if you set this, make sure to drain() (see step 3)
      min: options.connectionLimitMin || 0,
      // specifies how long a resource can stay idle in pool before being removed
      idleTimeoutMillis: 30000,
      // if true, logs via console.log - can also be a function
      log: process.env.DEBUG !== undefined
    });
  }

  const result = {};
  result.query = (sql) => {
    debug('wulian:mysql:query')(sql);
    const deferred = getDefer();
    db[key].acquire((err, client) => {
      if (err) {
        logger('wulian:mysql:pool', err);
        deferred.resolve({});
      } else {
        client.query(sql, [], (errQuery, rows) => {
          // return object back to pool
          // NOTICE:  `release` called after every query
          db[key].release(client);
          if (errQuery) {
            logger('wulian:mysql:query', errQuery);
            deferred.resolve({});
          }
          deferred.resolve(rows);
        });
      }
    });
    return deferred.promise;
  };
  // NOTICE: ignore release in project codes
  result.release = () => null;

  return result;
};
```

can it perform well?

**Comment by dougwilson** [comment]
Hi @willin, I'm not familiar enough with the `generic-pool` module to really say, as the built-in pool has been specifically designed to work with the MySQL connection lifecycle, including freshness checking.
