### ISSUE TITLE
strip backticks of string 

### ISSUE THREAD

**Issue by mwgi2005** [felixge/node-mysql#1442]
I'm using node-mysql as mysql connector, most of the value within the variables are sent by user and so I have use placeholder to prevent sql injection. In the code below "req.params.TableName" and "req.params.order" is sent by user, the table and order variable values are as following.
```

req.params.TableName = "officers"
req.params.order = asc OR desc
```

```
var table = [req.params.TableName, req.body.order];
var query = 'SELECT `officer_id` FROM ?? ORDER BY officer_id ??';
fullquery = mysql.format(query, table);
```

**Problem**

The above code generates following query, which give me a syntax error because of backticks around ASC, how do i remove these backticks ? thanks

`SELECT officer_id FROM `officers` ORDER BY officer_id `ASC`;`

**Note: Backticks on ASC are not shown here in the editior**

**Comment by dougwilson** [comment]
Hi @mwgi2005, I know you closed the issue before I could respond, but I'm going to respond anyway :) The reason it is not working is because you are misunderstanding what `?` and `??` actually does, that is quote values and quote identifiers. What you are putting in `req.body.order` is neither of those and is literal SQL, and there is no way to possibly escape any bad values in literal SQL, so I would suggest doing some kind of exact whitelist of what that value can be and appending it directly.

**Comment by mwgi2005** [comment]
Yeah I just did the same that's why i closed the issue, I used .replace tag to strip every thing except alphbets and numbers, and then appended the value directly without using the placeholder. do you think it is a good idea ? thanks anyways
