### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by AdriVanHoudt** [felixge/node-mysql#978]
Hi
I made a [hapi](http://www.hapijs.com) plugin for this lib. https://github.com/Salesflare/hapi-plugin-mysql
Now I'm getting some weird errors where sometimes it takes a long time for a request to complete (+/- 50000ms)
After a lot of searching we narrowed it down to probably the pooling. We suspect that getting a connection from the pool is taking a long time. 
Now I don't have a lot of experience with this lib so I was wondering if anyone can help me with reviewing my code. 

The `server.ext('onPreAuth',...` is called before each route and `server.ext('onPostHandler',...` is called after the I'm done with handling the route.

Any help or suggestions are appreciated!

**Comment by dougwilson** [comment]
I'll try my best to give some tips :)

  * So https://github.com/Salesflare/hapi-plugin-mysql/blob/master/lib/index.js#L45 is not necessary; `getConnection` already ensures that what you get is alive.
  * You need to call `connection.release()` in https://github.com/Salesflare/hapi-plugin-mysql/blob/master/lib/index.js#L70

Otherwise, it seems lie I have to have too much knowledge of how those Hapi events work and under what scenarios which ones fire and when they don't to really say more.

Perhaps if you can put together a really simple Hapi app that uses your module that demonstrates the error, I can look into it.

**Comment by AdriVanHoudt** [comment]
Thank you! 
And the events are called on every request to the server. Here is the life cycle http://hapijs.com/api#request-lifecycle
The problem is we don't know what the error is. It is just after a few hours in production some calls (super random) take a super long time to complete. Right now I added logging to practically every every step so I'll let you know if I find something with that.

**Comment by AdriVanHoudt** [comment]
Also `_endConnection` releases the connection so it is not needed on https://github.com/Salesflare/hapi-plugin-mysql/blob/master/lib/index.js#L70

**Comment by AdriVanHoudt** [comment]
Ok so I found out it was a table lock. 
```javascript
{ [Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction]
    app-0 (out):   code: 'ER_LOCK_WAIT_TIMEOUT',
    errno: 1205,
    sqlState: 'HY000',
    index: 0 }
```
Any suggestions on how to prevent/handle this?

**Comment by dougwilson** [comment]
This is really outside the scope of this module, since it's a database thing. To answer that, I would need to know all the queries you're doing, the length of time you are holding transactions open for and the standard lock order within your transactions.

**Comment by AdriVanHoudt** [comment]
3 queries: a select with some joins in it, a basic insert and a delete with some joins in
length depends on the duration of the request. And lock order doesn't ring a bell with me. :/

**Comment by AdriVanHoudt** [comment]
The lock always happens on the insert btw

**Comment by dougwilson** [comment]
Yes, but locking order depends on what keys are on the tables, what columns are in what order in the query and insert, etc. There is really way to much information needed to help you resolve a lock wait timeout here, unfortunately. You may want to post your whole MySQL schema along with exactly query texts to something like Stackoverflow.com to see if someone can help you determine what's happening. Typically it's because you are using incompatible locking order in your queries.
