### ISSUE TITLE
script trying to insert 12 million registers one by one

### ISSUE THREAD

**Issue by Muriloo** [felixge/node-mysql#987]
Hi,

My team wrote an script that will make 12 million requests to server, which would take 2 or 3 days to process (taking into account only the request time) and for each request we need to loop over the answers inserting several rows for each request.

We're currently using a pool with 15 connections, but when we get around the request of number 1 million we've core dump of the server (probably due to using more memory than available). We'll try to use V8 monitors to find where is the issue, but I'd like to understand a bit better how would the nodejs event loop handle all those requests, and also how the connection pool handle it.

I'd appreciate if you could give me an insight about it, suggest some other method to safely store the records, or recommend some material to read.

Thank you for your time, and I'm sorry for any wrong thing I might have said.

**Comment by sidorares** [comment]
Is [LOAD DATA INFILE](http://dev.mysql.com/doc/refman/5.1/en/load-data.html) an option for you? The problem with inserts is that client need to wait response for each insert. With load infile you basically send all rows as csv to server and rows are inserted in one batch. This could be days ws seconds time difference.

Also check that when you insert data autocomit is set to false - see "[Bulk Data Loading Tips](http://dev.mysql.com/doc/refman/5.1/en/innodb-tuning.html)"

**Comment by kai-koch** [comment]
Option A:
If the MySql-Server decides the Primary Key, use stored procedures or triggers, which puts stress on the mysql-server, but cuts down on network-traffic.

Option B:
If the Primary is already in the data, use multiple statements per request and fill parent and child-tables in one request, use more than one insert, if possible.
If HD speed of the Server becomes the bottle neck, use MySql-InnoDB and transactions. Transactions will reduce the writes to HD.

**Comment by kai-koch** [comment]
You also need to "slow down" node, since it seems to me your MySQL-Server not node is the bottleneck. Because if 1 million request pile up you DDOS your mysql server. :-)

**Comment by dougwilson** [comment]
So answering how the node.js event loop handles requests, etc. is out of scope of this MySQL module, but if you are crashing node.js because of a memory assertion while doing large bulk inserts, it is most likely an issue in your code.

When you call query in this library, we let you specify a callback function that tells you when the query is done. You can use this to know how much stuff you are building up in your memory; if you have too many rows in your memory at once, you will end up dumping from a OOM assertion. There are several tools you can use where you can periodically dump the memory (I think there is a heapdump module), which will tell you what is consuming all your memory.

The most important aspect, which was touched on above, is that you cannot accept in too many rows to your nodemjs process. Those query callbacks will be great and signaling to you when you can accept in more rows to your process and when you should deny more.

If you are not reading in these rows and instead they are coming in as requests, getting OOM assertions usually indicates it is time you need to start horizontal scaling.

**Comment by Muriloo** [comment]
I'd like to thank you all for the quick answers.

We'll study a bit more about headump, bulk load and InnoDB structure and make more attempts.
I come back here to say what worked and the analyzes we made.

Thank you!

**Comment by dougwilson** [comment]
Hi @Muriloo I'm going to close this issue since the last activity was a while ago, but please feel free to post comments on here or even open new issues if needed :)
